[[override]]
  name = "github.com/golang/protobuf"
  version = "=1.1.0"

[[override]]
  name = "github.com/tendermint/go-amino"
  version = "v0.14.0"

[[override]]
  name = "github.com/tendermint/tendermint"
  version = "v0.26.1-rc3" # TODO replace w/ 0.26.1

## deps without releases:

[[override]]
  name = "golang.org/x/crypto"
  source = "https://github.com/tendermint/crypto"
  revision = "3764759f34a542a3aef74d6b02e35be7ab893bba"

[[constraint]]
  name = "github.com/cosmos/go-bip39"
  revision = "52158e4697b87de16ed390e1bdaf813e581008fa"

## transitive deps, without releases:

[[override]]
  name = "github.com/syndtr/goleveldb"
  revision = "c4c61651e9e37fa117f53c5a906d3b63090d8445"

[prune]
  go-tests = true
  unused-packages = true
